### ISSUE TITLE
Swift 2

### ISSUE THREAD

**Issue by DavidCampus** [freedom27/MjpegStreamingKit#3]
Hi. I am using swift 2 for a project and I would love to use your framework to stream from my raspberry pi. Can I get the version of this framework before the swift 3 update?

**Comment by freedom27** [comment]
Hi, you can either clone this code and revert to a commit before the migration or wait this evening... I'll create a swift 2.0 branch

**Comment by freedom27** [comment]
Hi, I created swift_2.0 branch
